continue dowload after app reset
TryQuiet/monorepo pull request #710
Opened 2022-07-12 10:56 UTC by Dinek007

2022-07-12 13:03 UTC, siepra requested changes

2022-07-12 13:03 UTC, siepra commented on packages/state-manager/src/sagas/files/checkForMissingFiles/checkForMissingFiles.saga.test.ts
> +        Files: {
Same as above

2022-07-12 13:07 UTC, Dinek007 commented on packages/state-manager/src/sagas/files/checkForMissingFiles/checkForMissingFiles.saga.test.ts
> +      size: 1000
not `- 2048` ? it's case under the limit

2022-07-13 08:50 UTC, siepra commented on packages/state-manager/src/utils/tests/factories.ts
> +        if (payload.message.type === MessageType.File || MessageType.Image) {
What is that for? It should be saga's responsibilities to set proper download status for file (on incoming messages action)

2022-07-13 08:50 UTC, siepra commented on packages/state-manager/src/sagas/files/checkForMissingFiles/checkForMissingFiles.saga.ts
> +        if (file.size > AUTODOWNLOAD_SIZE_LIMIT || fileStatuses[file.message.id].downloadState === DownloadState.Canceled) return
Ideally it'd be two separate conditions, like that:

` if (file.size > AUTODOWNLOAD_SIZE_LIMIT) return`
` if (fileStatuses[file.message.id].downloadState === DownloadState.Canceled) return`

It's way better readable and easier to maintain

2022-07-13 08:50 UTC, siepra commented on packages/state-manager/src/sagas/files/checkForMissingFiles/checkForMissingFiles.saga.ts
> +  const fileStatuses = yield* select(filesSelectors.downloadStatuses)
It's minor but those are rather `downloadStatuses` than `fileStatuses`

2022-07-13 12:51 UTC, merged